# Generated by Django 5.2.7 on 2025-11-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colectividad',
            name='nombre',
            field=models.CharField(default='Colectividad', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colectividad',
            name='pais',
            field=models.CharField(default='Colectividad', max_length=100),
            preserve_default=False,
        ),
    ]
